services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ai-assist-api
    depends_on:
      - qdrant-server
    env_file:
      - .env
    environment:
      QDRANT_URL: qdrant-server
      DATA_DIR: /app/datasets
    ports:
      - "8000:8000"
    volumes:
      - ./datasets:/app/datasets:ro

  qdrant-server:
    image: qdrant/qdrant:v1.18-unprivileged
    restart: unless-stopped
    container_name: qdrant-server
    env_file:
      - .env
    expose:
      - 6333
      - 6334
      - 6335
    ports:
      - "6333:6333"
      - "6334:6334"
      - "6335:6335"
    volumes:
      - qdrant-storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__MAX_REQUEST_SIZE_MB: "4096"

    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml


volumes:
  qdrant-storage:


configs:
  qdrant_config:
    content: |
      log_level: INFO
