"""Generates figures/temporal_decay.tex, the ELES temporal-exclusion sweep.

Two panels sharing an x axis of exclusion window. The left panel shows how much of the archive
still supports an estimate; the right shows the error on the records that do. Read together
they separate two effects that a single exclusion window conflates: support falls away
continuously with the window, while the error penalty does not - it appears almost in full at
the narrowest window tested and barely grows thereafter.

Both panels carry reference lines for the unexcluded evaluation, and the right panel also
carries gradient boosting scored on each window's surviving records. That model does not
retrieve, so its line is flat by construction and shows what the same records are worth to a
method that does not depend on the archive's temporal structure.

Source is data/eles_temporal_exclusion_control.csv, the same artifact the Results text quotes.

Run from the repository root:
    uv run python scripts/paper/make_temporal_decay_figure.py
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import Final

import pandas as pd

PROJECT_DIR: Final[Path] = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_DIR))

from src.config.logging import configure_logging  # noqa: E402

logger = logging.getLogger(__name__)

PAPER_DIR: Final[Path] = PROJECT_DIR / "results"
DATA_PATH: Final[Path] = PAPER_DIR / "data" / "eles_temporal_exclusion_control.csv"
OUTPUT_PATH: Final[Path] = PAPER_DIR / "figures" / "temporal_decay.tex"

# The unexcluded evaluation: every state but the query itself is available. This must be the
# leave-one-state-out figure (data/eles_temporal_exclusion_control.csv, mae_baseline_marginal),
# not Table 2 retrieval MAE, which comes from the separate five-fold run and is a different
# protocol on a different population.
BASELINE_COVERAGE: Final[float] = 73.47
BASELINE_MAE: Final[float] = 0.049747
# The deployment rule, from data/eles_causal_evaluation.csv. Plotted as a reference because the
# sweep is a stress test and a reader needs to see where the operational figure actually sits.
CAUSAL_PATH: Final[Path] = PAPER_DIR / "data" / "eles_causal_evaluation.csv"

PREAMBLE: Final[str] = r"""% Generated by scripts/paper/make_temporal_decay_figure.py -- do not edit by hand.
% Redefined here rather than relying on the risk-coverage figure being input first.
\definecolor{okabeBlue}{HTML}{0072B2}
\definecolor{okabeVermillion}{HTML}{D55E00}
\definecolor{okabeGreen}{HTML}{009E73}
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=2 by 1, horizontal sep=1.35cm},
  width=0.47\textwidth, height=5.2cm,
  xmode=log, log basis x=2, xmin=2.2, xmax=66,
  xtick={3,6,12,24,48}, xticklabels={3,6,12,24,48},
  xlabel={Exclusion window (hours, $\pm$)},
  tick label style={font=\footnotesize}, label style={font=\footnotesize},
  title style={font=\footnotesize\bfseries},
  grid=major, grid style={gray!22, line width=0.3pt},
  every axis plot/.append style={line width=0.9pt, mark size=1.7pt},
  legend style={draw=none, fill=none, font=\footnotesize, legend columns=3,
                /tikz/every even column/.append style={column sep=10pt}},
]
"""


def _coords(xs: list[float], ys: list[float], fmt: str) -> str:
    return " ".join(f"({x:g},{y:{fmt}})" for x, y in zip(xs, ys, strict=True))


def _err_table(xs: list[float], ys: list[float], lo: list[float], hi: list[float]) -> str:
    """Inline table with explicit asymmetric error bars.

    pgfplots' coordinates form takes only symmetric bars via `+-`; there is no `-+`, and
    writing one typesets it as text, which floods the log with missing-character warnings and
    stalls the build. Asymmetric intervals have to go through a table with y error plus/minus.
    """
    rows = "\n".join(
        f"    {x:g} {y:.5f} {h - y:.5f} {y - lo_:.5f}" for x, y, lo_, h in zip(xs, ys, lo, hi, strict=True)
    )
    return "table[x=x,y=y,y error plus=ep,y error minus=em] {\n    x y ep em\n" + rows + "\n  }"


def main() -> None:
    configure_logging()
    df = pd.read_csv(DATA_PATH).sort_values("exclusion_hours")
    hours = df["exclusion_hours"].tolist()
    coverage = (df["coverage_control"] * 100).tolist()
    mae_ctrl = df["mae_control_paired"].tolist()
    mae_base_paired = df["mae_baseline_paired"].tolist()
    # The bootstrap gives a CI on the paired difference, so the interval on the control value is
    # that difference's interval offset from the same window's own baseline. Plotting the flat
    # full-population MAE instead would not be the quantity the percentages are computed from.
    err_lo = [b + lo for b, lo in zip(mae_base_paired, df["mae_diff_ci_low"], strict=True)]
    err_hi = [b + hi for b, hi in zip(mae_base_paired, df["mae_diff_ci_high"], strict=True)]
    causal = pd.read_csv(CAUSAL_PATH).iloc[0]
    causal_cov, causal_mae = float(causal["coverage_causal"]) * 100, float(causal["mae_causal_paired"])
    gb_col = "mae_hist_gradient_boosting_surviving"
    if gb_col not in df.columns:
        raise KeyError(f"{DATA_PATH.name} has no {gb_col}; re-run the control with the supervised comparison")
    mae_gb = df[gb_col].tolist()

    left = [
        "\\nextgroupplot[title={Support}, ylabel={Records with an estimate (\\%)}, ymin=0, ymax=80]",
        rf"\addplot[gray!65, dashed, line width=0.7pt, mark=none, forget plot] coordinates {{(2.2,{BASELINE_COVERAGE}) (66,{BASELINE_COVERAGE})}};",
        rf"\addplot[okabeGreen, dash dot, line width=0.8pt, mark=none, forget plot] coordinates {{(2.2,{causal_cov:.2f}) (66,{causal_cov:.2f})}};",
        rf"\addplot[color=okabeBlue, mark=*, mark options={{fill=okabeBlue}}, forget plot] coordinates {{{_coords(hours, coverage, '.2f')}}};",
    ]
    # The legend rides on the right panel and is anchored left of its origin so it centres
    # under the pair; all three series are declared here so one legend covers both panels.
    right = [
        "\\nextgroupplot[title={Error on supported records}, ylabel={MAE (s)}, ymin=0.04, ymax=0.115,"
        " legend style={at={(-0.14,-0.30)}, anchor=north},"
        " scaled y ticks=false, ytick={0.04,0.06,0.08,0.10},"
        " y tick label style={/pgf/number format/fixed, /pgf/number format/precision=2}]",
        rf"\addplot[gray!65, dashed, line width=0.7pt, mark=none] coordinates {{{_coords(hours, mae_base_paired, '.5f')}}};",
        rf"\addplot[okabeGreen, dash dot, line width=0.8pt, mark=none] coordinates {{(2.2,{causal_mae:.5f}) (66,{causal_mae:.5f})}};",
        "\\addplot[color=okabeBlue, mark=*, mark options={fill=okabeBlue}, error bars/.cd, y dir=both, y explicit] "
        + _err_table(hours, mae_ctrl, err_lo, err_hi)
        + ";",
        rf"\addplot[color=okabeVermillion, mark=diamond*, mark options={{fill=okabeVermillion}}] coordinates {{{_coords(hours, mae_gb, '.5f')}}};",
        r"\legend{{Query excluded only},{Causal, deployment rule},{Retrieval},{Gradient boosting}}",
    ]
    content = PREAMBLE + "\n".join(left + right) + "\n\\end{groupplot}\n\\end{tikzpicture}\n"
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    logger.info(f"Wrote {OUTPUT_PATH} ({len(hours)} windows)")


if __name__ == "__main__":
    main()
