"""Generates figures/risk_coverage.tex, the risk-coverage curves behind journal.tex Table 3.

Table 3 reports one nAURC number per diagnostic per dataset. That summarises a curve, and the
curve carries information the scalar hides: where in the coverage range a diagnostic helps,
that two diagnostics cross between datasets, and that a few curves are non-monotone. This
figure plots the underlying curves so those are visible.

Source is bootstrap_ci_selected_{bus39,eles-2026-06}.csv, the same artifact Table 3's point
estimates and CIs come from, so the figure and the table cannot disagree. Each metric's MAE is
divided by its own full-coverage MAE, which is exactly the normalisation inside nAURC: a curve
below 1.0 means withholding the least-trusted records lowers error, and a curve above 1.0
means the diagnostic orders records the wrong way round. That also puts both datasets on one
scale despite their very different absolute MAEs.

Run from the repository root:
    uv run python scripts/paper/make_risk_coverage_figure.py
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import Final

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.config.logging import configure_logging  # noqa: E402

logger = logging.getLogger(__name__)

PROJECT_DIR: Final[Path] = Path(__file__).resolve().parents[2]
PAPER_DIR: Final[Path] = PROJECT_DIR / "results"
DATA_DIR: Final[Path] = PAPER_DIR / "data"
OUTPUT_PATH: Final[Path] = PAPER_DIR / "figures" / "risk_coverage.tex"

PANELS: Final[tuple[tuple[str, str, str], ...]] = (
    ("BUS39", "bootstrap_ci_selected_bus39.csv", "bus39"),
    ("ELES", "bootstrap_ci_selected_eles-2026-06.csv", "eles/2026-06"),
)

# Display names match Table 3's row labels exactly, and the order matches its row order so the
# legend and the table read the same way. Colours are the Okabe-Ito colourblind-safe palette;
# each series also carries a distinct marker so the panels survive greyscale printing.
SERIES: Final[tuple[tuple[str, str, str, str], ...]] = (
    ("cct_weighted_std", "Weighted CCT dispersion", "okabeBlue", "*"),
    ("n_neighbors", "Retrieved neighbor count", "okabeSky", "oplus*"),
    # Dashed on purpose: on BUS39 this coincides exactly with "Retrieved neighbor count"
    # (K=100 binds, so each retrieved state contributes one neighbor). Drawn after it, a solid
    # stroke hides it completely. Dashing lets the series underneath show through the gaps.
    ("n_unique_states", "Unique supporting states", "okabeBlack", "star"),
    ("location_weight_mass", "Location support mass", "okabeOrange", "square*"),
    ("n_eff", "Effective sample size", "okabeGreen", "triangle*"),
    ("distance_min", "Minimum query distance", "okabeVermillion", "diamond*"),
    ("neighborhood_compactness", "Neighborhood compactness", "okabePurple", "pentagon*"),
)

# Series drawn with a dashed stroke so a coinciding series underneath stays visible. The
# style is applied in both panels, since one legend serves both and a series cannot change
# appearance between them.
DASHED_SERIES: Final[frozenset[str]] = frozenset({"n_unique_states"})

# The five published diagnostics come from bootstrap_ci_selected_*.csv; the two count
# diagnostics were added later and live in n_neighbors_selected_naurc.csv, restricted to the
# same Table 3 common-support population so all seven curves share one basis.
EXTRA_SOURCE: Final[str] = "n_neighbors_selected_naurc.csv"
EXTRA_METRICS: Final[frozenset[str]] = frozenset({"n_neighbors", "n_unique_states"})

PREAMBLE: Final[str] = r"""% Generated by scripts/paper/make_risk_coverage_figure.py -- do not edit by hand.
\definecolor{okabeBlue}{HTML}{0072B2}
\definecolor{okabeOrange}{HTML}{E69F00}
\definecolor{okabeGreen}{HTML}{009E73}
\definecolor{okabeVermillion}{HTML}{D55E00}
\definecolor{okabePurple}{HTML}{CC79A7}
\definecolor{okabeSky}{HTML}{56B4E9}
\definecolor{okabeBlack}{HTML}{000000}
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=2 by 1, horizontal sep=1.5cm},
  width=0.47\textwidth, height=5.4cm,
  xmin=0.47, xmax=1.03, xtick={0.5,0.6,0.7,0.8,0.9,1.0},
  xlabel={Coverage}, ylabel={MAE relative to full coverage},
  tick label style={font=\footnotesize}, label style={font=\footnotesize},
  title style={font=\footnotesize\bfseries},
  grid=major, grid style={gray!22, line width=0.3pt},
  every axis plot/.append style={line width=0.9pt, mark size=1.6pt},
  % The legend sits below and spans both panels. Left inside the axis it covered most of the
  % BUS39 plot area, which compiles perfectly cleanly and hides four of the five curves.
  legend style={draw=none, fill=none, font=\footnotesize, legend columns=3,
                /tikz/every even column/.append style={column sep=10pt}},
]
"""


def _panel(title: str, filename: str, dataset_key: str, with_legend: bool) -> str:
    df = pd.read_csv(DATA_DIR / filename)
    df = df[df["quantity"] == "mae"]

    extra = pd.read_csv(DATA_DIR / EXTRA_SOURCE)
    extra = extra[
        (extra["quantity"] == "mae")
        & (extra["population"] == "table3_common")
        & (extra["dataset"] == dataset_key)
        & (extra["metric"].isin(EXTRA_METRICS))
    ]
    df = pd.concat([df[["metric", "coverage", "point_estimate"]], extra[["metric", "coverage", "point_estimate"]]])

    pivot = df.pivot(index="coverage", columns="metric", values="point_estimate")
    missing = [name for name, _lbl, _c, _m in SERIES if name not in pivot.columns]
    if missing:
        raise KeyError(f"{title}: no coverage rows for {missing}")
    normalized = pivot / pivot.loc[1.0]
    # Anchor the limits to the 0.1 tick grid so every curve sits between labelled ticks.
    # Deriving ticks from an unrounded range instead drops the lowest tick on whichever panel
    # happens to start just above a multiple of 0.1, which is what hid BUS39's best curve.
    import math

    data_min = float(normalized.to_numpy().min())
    data_max = float(normalized.to_numpy().max())
    first_tick = math.floor(data_min * 10) / 10
    last_tick = math.ceil(data_max * 10) / 10
    lo = max(0.0, first_tick - 0.03)
    hi = last_tick + 0.03

    # Anchoring the legend at x=1.12 in the first panel's axis coordinates centres it under the
    # pair, accounting for the group's horizontal separation.
    legend_pos = ", legend style={at={(1.12,-0.26)}, anchor=north}" if with_legend else ""
    # Explicit 0.1-step ticks. Left to itself pgfplots picks a 0.2 step on BUS39, which labels
    # only 0.8 and 1.0 and leaves the best curve's lowest point below the lowest labelled tick.
    ticks = [round(0.1 * k, 1) for k in range(round(first_tick * 10), round(last_tick * 10) + 1)]
    tick_opt = ", ytick={" + ",".join(f"{v:.1f}" for v in ticks) + "}" if ticks else ""
    lines = [f"\\nextgroupplot[title={{{title}}}, ymin={lo:.2f}, ymax={hi:.2f}{tick_opt}{legend_pos}]"]
    # The no-skill reference: nAURC is defined against the unsorted baseline, so 1.0 is the
    # line a diagnostic has to get below to be doing anything at all.
    lines.append(
        r"\addplot[gray!65, dashed, line width=0.7pt, mark=none, forget plot] "
        r"coordinates {(0.47,1.0) (1.03,1.0)};"
    )
    for metric, _label, color, mark in SERIES:
        coords = " ".join(f"({cov:.2f},{normalized.loc[cov, metric]:.4f})" for cov in sorted(normalized.index))
        style = ", dashed" if metric in DASHED_SERIES else ""
        lines.append(
            f"\\addplot[color={color}, mark={mark}, mark options={{fill={color}, solid}}{style}] "
            f"coordinates {{{coords}}};"
        )
    if with_legend:
        entries = ",\n  ".join(f"{{{label}}}" for _m, label, _c, _mk in SERIES)
        lines.append(f"\\legend{{\n  {entries}\n}}")
    return "\n".join(lines)


def main() -> None:
    configure_logging()
    # The legend rides on the first panel: centring pgfplots' legend under a groupplot needs
    # extra positioning machinery and reads no better at this size.
    panels = [_panel(title, filename, key, with_legend=(i == 0)) for i, (title, filename, key) in enumerate(PANELS)]
    content = PREAMBLE + "\n".join(panels) + "\n\\end{groupplot}\n\\end{tikzpicture}\n"
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    logger.info(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
