"""Generates figures/burstiness.tex, how ELES topology groups sit in calendar time.

Two panels over the same quantity, a topology group's calendar span. The left panel gives its
cumulative distribution, once weighting each group equally and once weighting each state equally,
since large groups hold most of the states and a per-group curve alone would understate what a
typical query faces. The right panel plots span against group size, which is what makes the
manuscript's sentence about the *largest* groups checkable rather than an impression: if the big
groups were the durable ones, the cloud would rise to the right.

Both panels carry the record length as a reference. Without it the reader has no sense of scale,
and the whole point is the ratio between a group's span and the window it sits in.

Source is data/eles_topology_burstiness_groups.csv from eles_topology_burstiness.py.

Run from the repository root:
    uv run python scripts/paper/make_burstiness_figure.py
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import Final

import numpy as np
import pandas as pd

PROJECT_DIR: Final[Path] = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_DIR))

from src.config.logging import configure_logging  # noqa: E402

logger = logging.getLogger(__name__)

PAPER_DIR: Final[Path] = PROJECT_DIR / "results"
GROUPS_PATH: Final[Path] = PAPER_DIR / "data" / "eles_topology_burstiness_groups.csv"
SUMMARY_PATH: Final[Path] = PAPER_DIR / "data" / "eles_topology_burstiness.csv"
OUTPUT_PATH: Final[Path] = PAPER_DIR / "figures" / "burstiness.tex"
# Spans of exactly zero (every state in the group shares one timestamp) cannot be placed on a log
# axis. They are floored to half the sampling interval, which is where the data cannot resolve
# them anyway, rather than dropped: they are the most extreme cases of the effect being shown.
MIN_SPAN_DAYS: Final[float] = 1.0 / 48.0

PREAMBLE: Final[str] = r"""% Generated by scripts/paper/make_burstiness_figure.py -- do not edit by hand.
\definecolor{okabeBlue}{HTML}{0072B2}
\definecolor{okabeVermillion}{HTML}{D55E00}
\begin{tikzpicture}
\begin{groupplot}[
  group style={group size=2 by 1, horizontal sep=1.5cm},
  width=0.47\textwidth, height=5.2cm,
  xmode=log, xmin=0.018, xmax=400,
  xtick={0.0417,1,7,30,214}, xticklabels={1\,h,1\,d,1\,wk,1\,mo,214\,d},
  tick label style={font=\footnotesize}, label style={font=\footnotesize},
  title style={font=\footnotesize\bfseries},
  grid=major, grid style={gray!22, line width=0.3pt},
  legend style={draw=none, fill=none, font=\footnotesize},
]
"""


def _coords(xs, ys, yfmt: str = ".4f") -> str:
    return " ".join(f"({x:.5g},{y:{yfmt}})" for x, y in zip(xs, ys, strict=True))


def _ecdf(spans: np.ndarray, weights: np.ndarray, max_points: int = 220) -> tuple[np.ndarray, np.ndarray]:
    order = np.argsort(spans)
    x, w = spans[order], weights[order]
    y = 100.0 * np.cumsum(w) / w.sum()
    if len(x) > max_points:  # thin for file size; the curve is a step function of 736 points
        idx = np.unique(np.linspace(0, len(x) - 1, max_points).astype(int))
        x, y = x[idx], y[idx]
    return x, y


def main() -> None:
    configure_logging()
    g = pd.read_csv(GROUPS_PATH)
    summary = pd.read_csv(SUMMARY_PATH).set_index("quantity")["value"]
    record_days = float(summary["record_span_days"])
    large_min = int(summary["large_group_min_states"])

    multi = g[g["n_states"] >= 2].copy()
    multi["span"] = multi["span_days"].clip(lower=MIN_SPAN_DAYS)
    zero = int((multi["span_days"] == 0).sum())
    logger.info(f"{len(multi)} multi-state groups, {zero} with zero span floored to {MIN_SPAN_DAYS * 24:.0f} h")

    xg, yg = _ecdf(multi["span"].to_numpy(), np.ones(len(multi)))
    xs, ys = _ecdf(multi["span"].to_numpy(), multi["n_states"].to_numpy(float))

    left = [
        "\\nextgroupplot[title={Span of a topology group}, xlabel={Calendar span},"
        " ylabel={Cumulative (\\%)}, ymin=0, ymax=104, legend style={at={(0.93,0.28)}, anchor=east}]",
        rf"\addplot[gray!65, dashed, line width=0.7pt, mark=none, forget plot] coordinates {{({record_days:.4g},0) ({record_days:.4g},104)}};",
        rf"\addplot[okabeBlue, line width=1pt, mark=none] coordinates {{{_coords(xg, yg, '.2f')}}};",
        rf"\addplot[okabeVermillion, line width=1pt, densely dashed, mark=none] coordinates {{{_coords(xs, ys, '.2f')}}};",
        r"\legend{{By group},{By state}}",
    ]
    small = multi[multi["n_states"] < large_min]
    big = multi[multi["n_states"] >= large_min]
    right = [
        "\\nextgroupplot[title={Span against group size}, xlabel={Calendar span},"
        " ylabel={States in group}, ymode=log, ymin=1.6, ymax=90,"
        " ytick={2,5,10,20,50}, yticklabels={2,5,10,20,50}, legend style={at={(0.93,0.94)}, anchor=north east}]",
        rf"\addplot[gray!65, dashed, line width=0.7pt, mark=none, forget plot] coordinates {{({record_days:.4g},1.6) ({record_days:.4g},90)}};",
        "\\addplot[only marks, mark=*, mark size=0.9pt, color=okabeBlue, opacity=0.45] coordinates {"
        + _coords(small["span"], small["n_states"], ".0f")
        + "};",
        "\\addplot[only marks, mark=triangle*, mark size=1.9pt, color=okabeVermillion] coordinates {"
        + _coords(big["span"], big["n_states"], ".0f")
        + "};",
        rf"\legend{{{{$<{large_min}$ states}},{{$\geq{large_min}$ states}}}}",
    ]
    content = PREAMBLE + "\n".join(left + right) + "\n\\end{groupplot}\n\\end{tikzpicture}\n"
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8")
    logger.info(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
